openapi: "3.0.2"
info:
  title: Meile Subscription Plan API
  version: "1.0"
servers:
  - url: https://api.meile.mathnodes.com:5000/v1/
components:
  securitySchemes:
    name:
      type: "http"
      scheme: "basic"
  schemas:
    Plans:
      type: "array"
      items:
        $ref: "#/components/schemas/Plan"
    Nodes:
      type: "array"
      items:
        type: "string"
      example: ["sentnode143hrjwjrnyfktyc4yrdsq6nnhqya28nagwdm22", "sentnode1cwpf45cvluzty4k8t3f2h7s7y8r5rzrj7jahc2", "sentnode1dkh9wjjk00tee2rtnkxvw5t25s8yy74ehtwf6j", "sentnode1u5gk7dljfhh2cgczkvllsdh89sus5njsfs6509"]
    Subscriptions:
      type: "array"
      items:
        $ref: "#/components/schemas/Subscription"
    WalletAddress:
      type: "string"
      example: "sent14f3dy3qvl3tyg7helzy37amgwuf3qeh6t8pch8" 
    UUID: 
      type: "string"
      example: "6db9ac96-6222-4539-bfd8-440a2bf75948"
    AddData:
      type: "object"
      properties:
        wallet:
          type: "string"
          example: "sent14f3dy3qvl3tyg7helzy37amgwuf3qeh6t8pch8"
        plan_id:
          type: "int"
          format: "int64"
          example: "1123"
        duration:
          type: "int"
          format: "int64"
          example: "3"
        sub_id:
          type: "int"
          format: "int64"
          example: "31337"
        uuid:
          type: "string"
          example: "6db9ac96-6222-4539-bfd8-440a2bf75948"
        amt_paid:
          type: "int"
          format: "int64"
          example: "29325000000"
        denom:
          type: "string"
          example: "XMR"  
    AddResponse:
      type: "object"
      properties:      
        status:
          type: "boolean"
          example: "True"
        wallet:
          type: "string"
          example: "sent14f3dy3qvl3tyg7helzy37amgwuf3qeh6t8pch8"
        plan_id:
          type: "int"
          format: "int64"
          example: "31337"
        sub_id:
          type: "int"
          format: "int64"
          example: "1123"
        duration:
          type: "int"
          format: "int64"
          example: "3"
        tx:
          type: "string"
          example: "F9F219ECBEC6FAE03B30C21664AE227317587B278B21BAFEDFEC6918CABB6F78"
        message:
          type: "string"
          example: "Success."
        expires: 
          type: "string"
          example: "2023-12-25 01:02:18"
    Plan:
      type: "object"
      properties:
        uuid: 
          type: "string"
          example: "6db9ac96-6222-4539-bfd8-440a2bf75948"
        subscription_id:
          type: "int"
          format: "int64"
          example: "314159"
        plan_id:
          type: "int"
          format: "int64"
          example: "11828"
        plan_name:
          type: "string"
          example: "Meile Residential Subscription Plan"
        plan_price:
          type: "int"
          format: "int64"
          example: "15000"
        plan_denom:
          type: "string"
          example: "dvpn"
    Subscription:
      type: "object"
      properties:
        id: 
          type: "int"
          format: "int64"
          example: "31415"
        uuid: 
          type: "string"
          example: "6db9ac96-6222-4539-bfd8-440a2bf75948"
        wallet:
          type: "string"
          example: "sent14f3dy3qvl3tyg7helzy37amgwuf3qeh6t8pch8"  
        subscription_id:
          type: "int"
          format: "int64"
          example: "314159"
        plan_id:
          type: "int"
          format: "int64"
          example: "11828"
        amt_paid:
          type: "float"
          example: "15252.14"
        amt_denom:
          type: "string"
          example: "dvpn"
        subscribe_date:
          type: "string"
          example: "2023-09-25 01:02:18"    
        subscribe_duration:
          type: "int"
          example: "6"
        expires:
          type: "string"   
          example: "2023-12-25 01:02:18"
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /plans:
    get:
      summary: "Get current Meile Subscription Plans"
      description: "Get Meile Subscription Plans from Plan DB"
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Plans"        
                
  /subscription/{walletAddress}:
    get:
      description: "Get current Meile subscriptions via Sentinel wallet address"
      parameters: 
        - in: path
          name: walletAddress
          required: true
          schema:
            $ref: "#/components/schemas/WalletAddress"
          description: The user Sentinel wallet address
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscriptions"
  /add:
    post:
      description: ""
      parameters: 
        - in: header
          name: data
          required: true
          schema:
            $ref: "#/components/schemas/AddData"
          description: POST data required for adding a wallet to a Meile subscription plan
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddResponse"
              description: Data Returned on Success or Failure of adding Wallet to Meile Subscription Plan
  /nodes/{uuid}:
    get:
      description: "Get Nodes on Plan UUID"
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            $ref: "#/components/schemas/UUID"
          description: "UUID of Plan"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nodes"
              description: "The list of node addresses on Plan UUID."
            
security:
- BasicAuth: []

